title: "My 5th attempt at a site"
author: GitHub User #5
email: asdf@asdf.com
theme: minima
description:  This is my 5th attempt Need to edit a few more things.  jjj


# social links
twitter_username: trynumber5 # DO NOT include the @ character, or else the build will fail!
github_username:  TryNumber5 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
